import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { PaginatedResult } from '../common/interfaces/api-response.interface';
import { PaginationUtil } from '../common/utils/pagination.util';
import {
  MaintenanceLog,
  MaintenanceLogDocument,
} from '../maintenance-logs/schemas/maintenance-log.schema';
import { Mitra, MitraDocument } from '../mitras/schemas/mitra.schema';
import {
  Vehicle,
  VehicleDocument,
} from '../modules/vehicles/schemas/vehicle.schema';
import { Person, PersonDocument } from '../persons/schemas/person.schema';
import { Tree, TreeDocument } from '../trees/schemas/tree.schema';
import { CreateReportDto } from './dto/create-report.dto';
import { ReportQueryDto } from './dto/report-query.dto';
import { UpdateReportDto } from './dto/update-report.dto';
import { ReportRepository } from './repositories/report.repository';
import {
  Report,
  ReportDocument,
  ReportFileType,
  ReportType,
} from './schemas/report.schema';
import {
  buildCsv,
  buildSimplePdf,
  sanitizeFilename,
} from './utils/report-export.util';

export type ReportDownloadPayload = {
  buffer: Buffer;
  filename: string;
  contentType: string;
};

@Injectable()
export class ReportsService {
  constructor(
    private readonly reportRepository: ReportRepository,
    @InjectModel(Tree.name) private readonly treeModel: Model<TreeDocument>,
    @InjectModel(Person.name)
    private readonly personModel: Model<PersonDocument>,
    @InjectModel(Mitra.name) private readonly mitraModel: Model<MitraDocument>,
    @InjectModel(Vehicle.name)
    private readonly vehicleModel: Model<VehicleDocument>,
    @InjectModel(MaintenanceLog.name)
    private readonly maintenanceLogModel: Model<MaintenanceLogDocument>,
  ) {}

  async create(dto: CreateReportDto): Promise<Report> {
    return this.reportRepository.create(
      dto as unknown as Partial<ReportDocument>,
    );
  }

  async findAll(query: ReportQueryDto): Promise<PaginatedResult<Report>> {
    const options = PaginationUtil.parse(query);
    const baseFilter: Record<string, unknown> = {};
    if (query.reportType !== undefined) {
      baseFilter.reportType = query.reportType;
    }
    if (query.fileType !== undefined) {
      baseFilter.fileType = query.fileType;
    }
    if (query.status !== undefined) {
      baseFilter.status = query.status;
    }

    return this.reportRepository.findPaginated(options, baseFilter, [
      'reportName',
      'generatedBy',
      'locationFilter',
    ]);
  }

  async findOne(id: string): Promise<Report> {
    const entry = await this.reportRepository.findById(id);
    if (!entry) {
      throw new NotFoundException(`Report "${id}" not found`);
    }
    return entry;
  }

  async update(id: string, dto: UpdateReportDto): Promise<Report> {
    const updated = await this.reportRepository.updateById(
      id,
      dto as unknown as Partial<ReportDocument>,
    );
    if (!updated) {
      throw new NotFoundException(`Report "${id}" not found`);
    }
    return updated;
  }

  async remove(id: string): Promise<void> {
    const removed = await this.reportRepository.softDelete(id);
    if (!removed) {
      throw new NotFoundException(`Report "${id}" not found`);
    }
  }

  async buildDownload(id: string): Promise<ReportDownloadPayload> {
    const report = await this.findOne(id);
    const { headers, rows, summaryLines } = await this.collectReportData(report);
    const baseName = sanitizeFilename(report.reportName);
    const stamp = new Date().toISOString().slice(0, 10);

    if (report.fileType === ReportFileType.EXCEL) {
      const buffer = buildCsv(headers, rows);
      return {
        buffer,
        filename: `${baseName}_${stamp}.csv`,
        contentType: 'text/csv; charset=utf-8',
      };
    }

    const lines = [
      `Report: ${report.reportName}`,
      `Type: ${report.reportType}`,
      `Generated by: ${report.generatedBy}`,
      `Location: ${report.locationFilter || 'All'}`,
      `Period: ${this.fmtDate(report.startDate)} to ${this.fmtDate(report.endDate)}`,
      `Rows: ${rows.length}`,
      '',
      ...summaryLines,
      '',
      headers.join(' | '),
      '-'.repeat(72),
      ...rows.slice(0, 40).map((row) =>
        row.map((cell) => String(cell ?? '')).join(' | '),
      ),
      rows.length > 40 ? `...and ${rows.length - 40} more rows` : '',
    ].filter((line) => line !== undefined);

    return {
      buffer: buildSimplePdf('Paryavaran Prahri Report', lines),
      filename: `${baseName}_${stamp}.pdf`,
      contentType: 'application/pdf',
    };
  }

  private fmtDate(value?: Date | string) {
    if (!value) return '-';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '-';
    return d.toLocaleDateString('en-IN');
  }

  private locationMatch(filter?: string) {
    const q = filter?.trim();
    if (!q) return {};
    const rx = { $regex: q, $options: 'i' };
    return {
      $or: [
        { state: rx },
        { district: rx },
        { vidhanSabha: rx },
        { city: rx },
        { address: rx },
        { landName: rx },
        { location: rx },
      ],
    };
  }

  private dateRange(start: Date, end: Date, field = 'createdAt') {
    const from = new Date(start);
    from.setHours(0, 0, 0, 0);
    const to = new Date(end);
    to.setHours(23, 59, 59, 999);
    return { [field]: { $gte: from, $lte: to } };
  }

  private async collectReportData(report: Report): Promise<{
    headers: string[];
    rows: Array<Array<unknown>>;
    summaryLines: string[];
  }> {
    const loc = this.locationMatch(report.locationFilter);

    switch (report.reportType) {
      case ReportType.TREE_REPORT: {
        const items = await this.treeModel
          .find({
            ...loc,
            ...this.dateRange(report.startDate, report.endDate, 'plantedDate'),
          })
          .sort({ plantedDate: -1 })
          .limit(2000)
          .lean()
          .exec();
        return {
          headers: [
            'Tree ID',
            'Name',
            'Species',
            'Owner',
            'Mobile',
            'Land',
            'Status',
            'Planted Date',
          ],
          rows: items.map((t) => [
            t.treeId,
            t.treeName,
            t.species,
            t.userName,
            t.mobile,
            t.landName,
            t.status,
            this.fmtDate(t.plantedDate),
          ]),
          summaryLines: [`Total trees: ${items.length}`],
        };
      }
      case ReportType.PERSON_REPORT: {
        const items = await this.personModel
          .find({
            isDeleted: false,
            ...loc,
            ...this.dateRange(report.startDate, report.endDate),
          })
          .sort({ createdAt: -1 })
          .limit(2000)
          .lean()
          .exec();
        return {
          headers: ['Person ID', 'Name', 'Mobile', 'Email', 'City', 'State'],
          rows: items.map((p: any) => [
            p.personId,
            p.name,
            p.mobile,
            p.email,
            p.city,
            p.state,
          ]),
          summaryLines: [`Total persons: ${items.length}`],
        };
      }
      case ReportType.MITRA_REPORT: {
        const items = await this.mitraModel
          .find({
            isDeleted: false,
            ...loc,
            ...this.dateRange(report.startDate, report.endDate),
          } as any)
          .sort({ createdAt: -1 })
          .limit(2000)
          .lean()
          .exec();
        return {
          headers: [
            'Mitra ID',
            'Name',
            'Mobile',
            'Vidhan Sabha',
            'Status',
            'Membership',
          ],
          rows: items.map((m: any) => [
            m.mitraId,
            m.name,
            m.mobile,
            m.vidhanSabha,
            m.status,
            m.membership,
          ]),
          summaryLines: [`Total mitras: ${items.length}`],
        };
      }
      case ReportType.VEHICLE_REPORT: {
        const items = await this.vehicleModel
          .find({
            isDeleted: false,
            ...this.dateRange(report.startDate, report.endDate),
          } as any)
          .sort({ createdAt: -1 })
          .limit(2000)
          .lean()
          .exec();
        return {
          headers: ['Vehicle ID', 'Plate', 'Name', 'Fuel', 'Insurance ID'],
          rows: items.map((v: any) => [
            v.vhId,
            v.plate,
            v.name,
            v.fuel,
            v.insuranceId,
          ]),
          summaryLines: [`Total vehicles: ${items.length}`],
        };
      }
      case ReportType.ACTIVITY_REPORT:
      default: {
        const items = await this.maintenanceLogModel
          .find({
            isDeleted: false,
            ...this.dateRange(report.startDate, report.endDate, 'loggedAt'),
          })
          .sort({ loggedAt: -1 })
          .limit(2000)
          .lean()
          .exec();
        return {
          headers: [
            'Tree Code',
            'Activity',
            'Remarks',
            'Mitra ID',
            'Logged By',
            'Logged At',
          ],
          rows: items.map((log) => [
            log.treeCode,
            log.activity,
            log.remarks,
            log.mitraId,
            log.createdByName,
            this.fmtDate(log.loggedAt),
          ]),
          summaryLines: [`Total maintenance activities: ${items.length}`],
        };
      }
    }
  }

  /**
   * Monthly plantation counts for Admin Preview / Mitra charts.
   * Groups trees by calendar month of plantedDate (fallback: createdAt).
   */
  async getMonthlyPlantations(query: {
    months?: number;
    vidhanSabha?: string;
    mitraId?: string;
  }) {
    const months = Math.min(Math.max(Number(query.months) || 6, 1), 24);
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth() - (months - 1), 1);

    const match: Record<string, unknown> = {
      $or: [
        { plantedDate: { $gte: start } },
        {
          plantedDate: { $exists: false },
          createdAt: { $gte: start },
        },
        {
          plantedDate: null,
          createdAt: { $gte: start },
        },
      ],
    };
    if (query.vidhanSabha?.trim()) {
      match.vidhanSabha = query.vidhanSabha.trim();
    }
    if (query.mitraId?.trim()) {
      const id = query.mitraId.trim();
      match.assignedMitraId = Types.ObjectId.isValid(id)
        ? new Types.ObjectId(id)
        : id;
    }

    const trees = await this.treeModel
      .find(match)
      .select('plantedDate createdAt status')
      .lean()
      .exec();

    const buckets: Array<{
      key: string;
      label: string;
      year: number;
      month: number;
      count: number;
      alive: number;
      dead: number;
    }> = [];

    for (let i = 0; i < months; i++) {
      const d = new Date(start.getFullYear(), start.getMonth() + i, 1);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
      buckets.push({
        key,
        label: d.toLocaleString('en-GB', { month: 'short' }),
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        count: 0,
        alive: 0,
        dead: 0,
      });
    }

    const byKey = new Map(buckets.map((b) => [b.key, b]));

    for (const tree of trees) {
      const raw = (tree as any).plantedDate || (tree as any).createdAt;
      if (!raw) continue;
      const date = new Date(raw);
      if (Number.isNaN(date.getTime()) || date < start) continue;
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
      const bucket = byKey.get(key);
      if (!bucket) continue;
      bucket.count += 1;
      const status = String((tree as any).status || '').toUpperCase();
      if (status === 'DEAD') bucket.dead += 1;
      else bucket.alive += 1;
    }

    const total = buckets.reduce((sum, b) => sum + b.count, 0);
    const maxCount = Math.max(...buckets.map((b) => b.count), 1);

    return {
      months: buckets.map((b) => ({
        ...b,
        /** 0–100 bar height helper for charts */
        heightPct: Math.round((b.count / maxCount) * 100),
      })),
      total,
      from: start.toISOString(),
      to: now.toISOString(),
    };
  }
}
